# Generated by Django 4.1 on 2023-07-04 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taskapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="date",
            field=models.DateField(default="1993-04-23"),
            preserve_default=False,
        ),
    ]
